# This file was generated by GoReleaser. DO NOT EDIT.
cask "chezit" do
  version "0.2.1"

  on_macos do
    on_intel do
      url "https://github.com/daptify14/chezit/releases/download/v#{version}/chezit_#{version}_darwin_amd64.tar.gz"
      sha256 "8b5c8875d2bddec985bafa460dd6efdf4320cac6de75a3d4d684757881add24e"
    end
    on_arm do
      url "https://github.com/daptify14/chezit/releases/download/v#{version}/chezit_#{version}_darwin_arm64.tar.gz"
      sha256 "6eefe36e4a4e90358c9b9bc06024484c6e8d9fb9861d3c0cad2b155f55c0b626"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/daptify14/chezit/releases/download/v#{version}/chezit_#{version}_linux_amd64.tar.gz"
      sha256 "3a5b3eb88f2cadd09d5ddd3a7b59821cc5185e1ec6a6a05dfa310747f0af6a4e"
    end
    on_arm do
      url "https://github.com/daptify14/chezit/releases/download/v#{version}/chezit_#{version}_linux_arm64.tar.gz"
      sha256 "c67b8a50e7ef5fdc604c13e6b2d2d2337a96d95fdcf665af7c1e8a09dadc1bb2"
    end
  end

  name "chezit"
  desc "Terminal UI for chezmoi dotfile management"
  homepage "https://github.com/daptify14/chezit"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "chezit"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/chezit"]
    end
  end

  # No zap stanza required

end
