# This file was generated by GoReleaser. DO NOT EDIT.
cask "chezit" do
  version "0.2.2"

  on_macos do
    on_intel do
      sha256 "38a26db50d7527e37109bcd3f325af0858f0ad25a5c5e734a5ca75102330ac53"
      url "https://github.com/daptify14/chezit/releases/download/v#{version}/chezit_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "28165ea1304f7adf2d19c9ba0fc2c2155d552cbc9aca09ec60a626835ce75dd7"
      url "https://github.com/daptify14/chezit/releases/download/v#{version}/chezit_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "6eba52dbc5555290371a784822d02bcda96880b410fd5dbfccab457488c4a5a9"
      url "https://github.com/daptify14/chezit/releases/download/v#{version}/chezit_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "e044ef343c551c7b2a47fced848e010dc34ff33a3a39d0f436648cfa81ebe923"
      url "https://github.com/daptify14/chezit/releases/download/v#{version}/chezit_#{version}_linux_arm64.tar.gz"
    end
  end

  name "chezit"
  desc "Terminal UI for chezmoi dotfile management"
  homepage "https://github.com/daptify14/chezit"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "chezit"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/chezit"]
    end
  end

  # No zap stanza required

end
