# This file was generated by GoReleaser. DO NOT EDIT.
cask "chezit" do
  name "chezit"
  desc "Terminal UI for chezmoi dotfile management"
  homepage "https://github.com/daptify14/chezit"
  version "0.2.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "chezit"

  on_macos do
    on_intel do
      url "https://github.com/daptify14/chezit/releases/download/v#{version}/chezit_#{version}_darwin_amd64.tar.gz"
      sha256 "3fffc78fb25ec45b4f3dd10f73b5f123840abccd602a08930a51a4e6641ae01a"
    end
    on_arm do
      url "https://github.com/daptify14/chezit/releases/download/v#{version}/chezit_#{version}_darwin_arm64.tar.gz"
      sha256 "6b6130fee4c101adecf060df62ca06d84b185bcc3ca9e01c2a3919947cf8d906"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/daptify14/chezit/releases/download/v#{version}/chezit_#{version}_linux_amd64.tar.gz"
      sha256 "0f131b1b7ee4158742684db2eadd9389cb663e0fb82f84c54500e78ad323085e"
    end
    on_arm do
      url "https://github.com/daptify14/chezit/releases/download/v#{version}/chezit_#{version}_linux_arm64.tar.gz"
      sha256 "f4786e1b1c9e11ae0ab7bdc3aabb2e1081d215148ffc9f2ea8f7490856945eac"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/chezit"]
    end
  end

  # No zap stanza required
end
